### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by co3d** [hpbieker/homebridge-yr#1]
Hi!

Thanks for building this plugin, looks amazing.
I´m having issues installing it, this is the logging error:

> node-expat@2.3.16 install /usr/local/lib/node_modules/homebridge-yr/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-yr/node_modules/node-expat/build'
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-yr/node_modules/node-expat
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/local/.npm/_logs/2017-11-11T12_07_00_918Z-debug.log

Any idea?

Thanks :)

**Comment by hpbieker** [comment]
Which OS do you use? And which command did you run to install? Are you running as root?

**Comment by co3d** [comment]
Thanks for answering.

I’m using OSX El Capitan because is an old Mac and used sudo with the code you gave.

**Comment by hpbieker** [comment]
Hi,

I do not know about Mac, but this is the output I get when installing homebridge-yr ong Linux (using docker). I suggest you try adding "--unsafe-perm" to the command.
~~~
Step 4/4 : RUN npm install -g --unsafe-perm homebridge-yr
 ---> Running in a9ea9fb2850c

> node-expat@2.3.16 install /usr/local/lib/node_modules/homebridge-yr/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-yr/node_modules/xml2json/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function 'gather_time_entropy':
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable 'gettimeofday_res' set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  COPY Release/node_expat.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-yr/node_modules/xml2json/node_modules/node-expat/build'
homebridge-yr@1.0.0 /usr/local/lib/node_modules/homebridge-yr
 request@2.83.0 (aws-sign2@0.7.0, oauth-sign@0.8.2, tunnel-agent@0.6.0, forever-agent@0.6.1, caseless@0.12.0, is-typedarray@1.0.0, safe-buffer@5.1.1,
stringstream@0.0.5, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.1, performance-now@2.1.0, uuid@3.1.0, qs@6.5.1, combined-stream@
1.0.5, tough-cookie@2.3.3, form-data@2.3.1, mime-types@2.1.17, hawk@6.0.2, http-signature@1.2.0, har-validator@5.0.3)
 xml2json@0.11.0 (hoek@4.2.0, joi@9.2.0, node-expat@2.3.16)
 ---> 2de7e9d95b60
~~~

Here is the Dockerfile I used:
~~~
FROM node:4
RUN apt-get update && apt-get install -y libavahi-compat-libdnssd-dev
RUN npm install -g --unsafe-perm homebridge
RUN npm install -g --unsafe-perm homebridge-yr
~~~

I also just verified with node 9 and node 8, and it installs without problems. If it still does not work for you, please check the node and npm versions:
~~~
# node -v
v4.8.6
# npm -v
2.15.11
~~~

**Comment by co3d** [comment]
Awesome!
It did work :)

Thanks a lot for your help, as you can see I´m brand new in this.
